image: python:3.7-slim

pages:
  script:
  - pip install -r requirements.txt
  - pip install sphinx
  - sphinx-build -d html doc doc/_build
  - mv doc/_build/html public
  artifacts:
    paths:
    - public
  only:
  - master
