image: python:3.7-slim

pages:
  script:
  - apk update
  - apk --no-cache --update-cache add gcc gfortran python3-dev py-pip build-base wget freetype-dev libpng-dev openblas-dev
  - apk add make automake gcc g++ subversion python3-dev
  - pip install -r requirements.txt
  - pip install -U sphinx
  - sphinx-build -d doc doc/_build
  - mv doc/_build/html public
  artifacts:
    paths:
    - public
  only:
  - master
