image: python:3.7-alpine

pages:
  script:
  - apk update
  - apk add make automake gcc g++ subversion python3-dev
  - pip install -r requirements.txt
  - pip install -U sphinx
  - sphinx-build -d doc doc/_build
  - mv doc/_build/html public
  artifacts:
    paths:
    - public
  only:
  - master
